// <auto-generated />
using System;
using AltinKaynak.GetCurrency.ASMX;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace altinkaynak.Migrations
{
    [DbContext(typeof(KurContext))]
    [Migration("20251201172503_InitalCreate")]
    partial class InitalCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AltinKaynak.GetCurrency.ASMX.Model.Altin", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Aciklama")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Alis")
                        .HasColumnType("float");

                    b.Property<string>("AltinTipi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Satis")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("Altinlar");
                });

            modelBuilder.Entity("AltinKaynak.GetCurrency.ASMX.Model.Kur", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Aciklama")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Alis")
                        .HasColumnType("float");

                    b.Property<DateTime?>("GuncellemeZamani")
                        .HasColumnType("datetime2");

                    b.Property<string>("KurKodu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KurTipi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Satis")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("Kurlar");
                });
#pragma warning restore 612, 618
        }
    }
}
